In [1]:
import numpy as np
import pandas as pd

In [5]:
import zipfile

with zipfile.ZipFile('archive (1).zip', 'r') as zip_ref:
    print(zip_ref.namelist())

['customer.csv']

In [6]:
import zipfile

with zipfile.ZipFile('archive (1).zip', 'r') as zip_ref:
    zip_ref.extractall()

In [9]:
df = pd.read_csv('customer.csv')
df.sample(5)

    age  gender   review education purchased
19   97    Male     Poor        PG       Yes
49   25  Female     Good        UG        No
16   59    Male     Poor        UG       Yes
41   23    Male     Good        PG       Yes
32   92    Male  Average        UG       Yes

In [25]:
from sklearn.model_selection import train_test_split

X = df[['age', 'gender']]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [26]:
print(X_train.dtypes)

age        int64
gender    object
dtype: object

In [27]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

X_train[['gender']] = oe.fit_transform(X_train[['gender']])

X_train.head()

    age  gender
12   51     1.0
4    16     0.0
37   94     1.0
8    65     0.0
3    72     0.0

In [28]:
X_train['gender'] = X_train['gender'].map({
    'Female': 0,
    'Male': 1
})

In [29]:
print(X_train.dtypes)
print(X_train.head())
print(X_train['gender'].unique())

age         int64
gender    float64
dtype: object
    age  gender
12   51     NaN
4    16     NaN
37   94     NaN
8    65     NaN
3    72     NaN
[nan]

In [30]:
X_train.head()

    age  gender
12   51     NaN
4    16     NaN
37   94     NaN
8    65     NaN
3    72     NaN

In [31]:
X_test[['gender']] = oe.transform(X_test[['gender']])

In [32]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [10]:
df=df.iloc[:,:2]

In [11]:
df.head()

   age  gender
0   30  Female
1   68  Female
2   70  Female
3   72  Female
4   16  Female

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:2],df.iloc[:,-1],test_size=0.2)

In [13]:
X_train

    age  gender
32   92    Male
47   38  Female
45   61    Male
6    18    Male
27   69  Female
8    65  Female
1    68  Female
46   64  Female
30   73    Male
43   27    Male
0    30  Female
7    60  Female
12   51    Male
35   74    Male
36   34  Female
9    74    Male
33   89  Female
25   57  Female
15   75    Male
14   15    Male
24   16  Female
34   86    Male
18   19    Male
39   76    Male
26   53  Female
38   45  Female
29   83  Female
13   57  Female
16   59    Male
5    31  Female
28   48    Male
4    16  Female
17   22  Female
10   98  Female
37   94    Male
3    72  Female
20   57  Female
40   39    Male
22   18  Female
21   32    Male

In [21]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Female', 'Male']])

oe.fit(X_train[['gender']])

X_train['gender'] = oe.transform(X_train[['gender']])

ValueError: could not convert string to float: 'Female'

In [22]:
X_train[['gender']].head()

    gender
32     1.0
47     0.0
45     1.0
6      1.0
27     0.0

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
X_train[['gender']].dtypes

gender    float64
dtype: object

In [17]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [20]:
oe.fit(X_train)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [15]:
X_train

    age  gender
32   92    Male
47   38  Female
45   61    Male
6    18    Male
27   69  Female
8    65  Female
1    68  Female
46   64  Female
30   73    Male
43   27    Male
0    30  Female
7    60  Female
12   51    Male
35   74    Male
36   34  Female
9    74    Male
33   89  Female
25   57  Female
15   75    Male
14   15    Male
24   16  Female
34   86    Male
18   19    Male
39   76    Male
26   53  Female
38   45  Female
29   83  Female
13   57  Female
16   59    Male
5    31  Female
28   48    Male
4    16  Female
17   22  Female
10   98  Female
37   94    Male
3    72  Female
20   57  Female
40   39    Male
22   18  Female
21   32    Male